version: '2'

services:
  node:
    image: node:11
    ports:
      - 4000:4000
    working_dir: /node
    volumes:
      - ./node:/node
      - /node/node_modules
      - ./data:/node/data
    depends_on:
      - postgres
    command: bash -c "yarn && yarn dev"

  postgres:
    image: postgres
    volumes: 
      - ./postgres:/var/lib/postgresql/
    ports:
      - 5000:5432
    environment:
      POSTGRES_USER: tasteit
      POSTGRES_PASSWORD: EkHMphfkH7raPWFvZnPxQdSh9ZpLHeeUK8r9mG5QAAct77HenN
      POSTGRES_DB: tasteit
      
    ##name: postgresdb
    
